# Generated by Django 5.1.6 on 2025-02-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0004_appoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appoint',
            new_name='appointment',
        ),
    ]
